name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting tools (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install "black==24.8.0" "ruff==0.5.4"

      - name: Show versions
        run: |
          black --version
          ruff --version
          python --version

      - name: Lint (ruff + black --check)
        run: |
          ruff check .
          black --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov

      - name: Test (pytest + coverage)
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=pipeline_360 --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
